<script lang="ts">
	import { page } from '$app/stores';
	import Icon from '$lib/components/shared/Icon.svelte';
	import StatusBadge from '$lib/components/shared/StatusBadge.svelte';
	import Modal from '$lib/components/shared/Modal.svelte';
	import PipelineView from '$lib/components/changes/PipelineView.svelte';
	import DocumentPanel from '$lib/components/changes/DocumentPanel.svelte';
	import TaskList from '$lib/components/changes/TaskList.svelte';
	import { changesStore } from '$lib/stores/changes.svelte';
	import { derivePipelineState, type DocumentInfo, type ParsedTask } from '$lib/types/changes';
	import { onMount } from 'svelte';

	const slug = $derived($page.params.slug);
	const change = $derived(slug ? changesStore.getBySlug(slug) : undefined);
	const pipeline = $derived(
		change ? derivePipelineState(change.files, change.active_loops) : null
	);

	let documents = $state<DocumentInfo[]>([]);
	let tasks = $state<ParsedTask[]>([]);
	let selectedDoc = $state<string | undefined>(undefined);
	let showDocModal = $state(false);

	onMount(async () => {
		await changesStore.fetch();
		if (slug) {
			documents = await changesStore.getDocuments(slug);
			tasks = await changesStore.getTasks(slug);
		}
	});

	function handleStageClick(stage: string) {
		selectedDoc = stage;
		showDocModal = true;
	}

	function handleDocSelect(type: string) {
		selectedDoc = type;
		showDocModal = true;
	}

	const selectedDocument = $derived(documents.find((d) => d.type === selectedDoc));

	async function handleApprove() {
		if (change) {
			await changesStore.approve(change.slug);
		}
	}
</script>

<svelte:head>
	<title>{change?.slug || 'Change'} - Semspec</title>
</svelte:head>

<div class="change-detail">
	<header class="detail-header">
		<a href="/changes" class="back-link">
			<Icon name="chevron-left" size={16} />
			Back to Changes
		</a>
	</header>

	{#if !change}
		<div class="not-found">
			<Icon name="alert-circle" size={48} />
			<h2>Change not found</h2>
			<p>The change "{slug}" could not be found.</p>
			<a href="/changes" class="btn btn-primary">Back to Changes</a>
		</div>
	{:else}
		<div class="change-info">
			<h1 class="change-title">{change.slug}</h1>
			<div class="change-meta">
				<StatusBadge status={change.status} size="md" />
				<span class="separator">|</span>
				<span>Author: {change.author}</span>
				{#if change.github}
					<span class="separator">|</span>
					<a
						href={change.github.epic_url}
						target="_blank"
						rel="noopener noreferrer"
						class="github-link"
					>
						<Icon name="external-link" size={14} />
						GH #{change.github.epic_number}
					</a>
				{/if}
			</div>
		</div>

		{#if pipeline}
			<PipelineView
				{pipeline}
				{documents}
				onStageClick={handleStageClick}
			/>
		{/if}

		{#if change.status === 'reviewed'}
			<div class="approval-banner">
				<Icon name="alert-triangle" size={20} />
				<div class="approval-content">
					<strong>Ready for approval</strong>
					<p>The spec has been reviewed. Approve to generate implementation tasks.</p>
				</div>
				<button class="btn btn-primary" onclick={handleApprove}>
					Approve Spec
				</button>
			</div>
		{/if}

		<div class="detail-content">
			<div class="documents-section">
				<DocumentPanel
					{documents}
					selectedType={selectedDoc}
					onSelect={handleDocSelect}
				/>
			</div>

			<div class="tasks-section">
				<TaskList {tasks} activeLoops={change.active_loops} />
			</div>
		</div>
	{/if}
</div>

{#if showDocModal && selectedDocument}
	<Modal
		title="{selectedDocument.type}.md"
		onClose={() => (showDocModal = false)}
	>
		{#if selectedDocument.content}
			<div class="doc-meta">
				{#if selectedDocument.model}
					<span>Generated by: {selectedDocument.model}</span>
				{/if}
				{#if selectedDocument.generated_at}
					<span>{new Date(selectedDocument.generated_at).toLocaleString()}</span>
				{/if}
			</div>
			<div class="doc-content">
				<pre>{selectedDocument.content}</pre>
			</div>
		{:else}
			<p class="no-content">Document content not available.</p>
		{/if}
	</Modal>
{/if}

<style>
	.change-detail {
		padding: var(--space-6);
		max-width: 1200px;
		margin: 0 auto;
	}

	.detail-header {
		margin-bottom: var(--space-4);
	}

	.back-link {
		display: inline-flex;
		align-items: center;
		gap: var(--space-1);
		color: var(--color-text-muted);
		text-decoration: none;
		font-size: var(--font-size-sm);
	}

	.back-link:hover {
		color: var(--color-text-primary);
	}

	.not-found {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: var(--space-3);
		padding: var(--space-12) 0;
		color: var(--color-text-muted);
		text-align: center;
	}

	.not-found h2 {
		margin: 0;
		color: var(--color-text-primary);
	}

	.change-info {
		margin-bottom: var(--space-4);
	}

	.change-title {
		font-size: var(--font-size-2xl);
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
		margin: 0 0 var(--space-2);
	}

	.change-meta {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
	}

	.separator {
		color: var(--color-border);
	}

	.github-link {
		display: inline-flex;
		align-items: center;
		gap: var(--space-1);
		color: var(--color-accent);
	}

	.approval-banner {
		display: flex;
		align-items: center;
		gap: var(--space-4);
		padding: var(--space-4);
		background: var(--color-warning-muted);
		border: 1px solid var(--color-warning);
		border-radius: var(--radius-lg);
		margin-bottom: var(--space-6);
		color: var(--color-warning);
	}

	.approval-content {
		flex: 1;
	}

	.approval-content strong {
		display: block;
		color: var(--color-text-primary);
	}

	.approval-content p {
		margin: var(--space-1) 0 0;
		font-size: var(--font-size-sm);
		color: var(--color-text-secondary);
	}

	.detail-content {
		display: grid;
		grid-template-columns: 250px 1fr;
		gap: var(--space-6);
		padding-top: var(--space-6);
		border-top: 1px solid var(--color-border);
	}

	.documents-section,
	.tasks-section {
		overflow: hidden;
	}

	.doc-meta {
		display: flex;
		gap: var(--space-4);
		margin-bottom: var(--space-4);
		padding-bottom: var(--space-3);
		border-bottom: 1px solid var(--color-border);
		font-size: var(--font-size-sm);
		color: var(--color-text-muted);
	}

	.doc-content {
		max-height: 60vh;
		overflow-y: auto;
	}

	.doc-content pre {
		white-space: pre-wrap;
		font-family: var(--font-family-mono);
		font-size: var(--font-size-sm);
		line-height: var(--line-height-relaxed);
		color: var(--color-text-primary);
	}

	.no-content {
		color: var(--color-text-muted);
		text-align: center;
		padding: var(--space-8);
	}
</style>
