package githubsubmitter

import (
	"fmt"
	"strings"

	"github.com/c360studio/semspec/workflow"
)

// BuildPRBody constructs a pull request body from plan data.
func BuildPRBody(plan *workflow.Plan) string {
	var sb strings.Builder

	sb.WriteString("## Summary\n")
	if plan.GitHub != nil && plan.GitHub.IssueNumber > 0 {
		sb.WriteString(fmt.Sprintf("Fixes #%d\n\n", plan.GitHub.IssueNumber))
	}
	if plan.Goal != "" {
		sb.WriteString(plan.Goal)
		sb.WriteString("\n\n")
	}

	if len(plan.Requirements) > 0 {
		sb.WriteString("## Requirements\n")
		for _, r := range plan.Requirements {
			if r.Status == workflow.RequirementStatusActive {
				sb.WriteString(fmt.Sprintf("- [x] %s\n", r.Title))
			} else if r.Status == workflow.RequirementStatusDeprecated {
				sb.WriteString(fmt.Sprintf("- [ ] ~%s~ (deprecated)\n", r.Title))
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n")
	sb.WriteString("Generated by [semspec](https://github.com/c360studio/semspec)")
	if plan.GitHub != nil && plan.GitHub.IssueNumber > 0 {
		sb.WriteString(fmt.Sprintf(" from #%d", plan.GitHub.IssueNumber))
	}
	sb.WriteString("\n")

	return sb.String()
}
