version: "3"

includes:
  e2e: ./taskfiles/e2e.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build semspec binary
    cmds:
      - go build -o bin/semspec ./cmd/semspec

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf test/e2e/workspace/.semspec/

  ui:install:
    desc: Install UI dependencies
    dir: ui
    cmds:
      - npm install

  ui:dev:
    desc: Start UI dev server (requires task e2e:up first)
    dir: ui
    cmds:
      - npm run dev

  ui:build:
    desc: Build UI static files
    dir: ui
    cmds:
      - npm run build
