version: "3"

dotenv: ['.env']

includes:
  e2e: ./taskfiles/e2e.yml
  generate: ./taskfiles/generate.yml
  lint:
    taskfile: ./taskfiles/lint.yml
    aliases: [l]

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build semspec binary
    cmds:
      - go build -o bin/semspec ./cmd/semspec

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  check:
    desc: Run all checks (lint + test)
    cmds:
      - task: lint:default
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf test/e2e/workspace/.semspec/

  ui:install:
    desc: Install UI dependencies
    dir: ui
    cmds:
      - npm install

  ui:dev:
    desc: Start UI dev server (requires task e2e:up first)
    dir: ui
    cmds:
      - npm run dev

  ui:build:
    desc: Build UI static files
    dir: ui
    cmds:
      - npm run build

  local:up:
    desc: Start local dev stack (builds from source)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.local.yml up -d --build

  local:down:
    desc: Stop local dev stack
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.local.yml down

  local:logs:
    desc: Tail local dev stack logs
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.local.yml logs -f

  local:rebuild:
    desc: Rebuild and restart semspec only (faster iteration)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.local.yml up -d --build semspec
