/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/constitution/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get constitution
         * @description Returns the current project constitution with all sections and rules
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Constitution with all sections and rules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constitution/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check content
         * @description Check content against all constitution rules and return violations and warnings
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Check result with pass/fail status, violations, and warnings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPCheckResponse"];
                    };
                };
                /** @description Invalid request (missing content field) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constitution/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload constitution
         * @description Reload the constitution from the configured file path
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reload result with success status and rule count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReloadResponse"];
                    };
                };
                /** @description Failed to reload constitution */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constitution/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all rules
         * @description Returns all rules across all sections with their section information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all rules with section metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RulesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constitution/rules/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rules by section
         * @description Returns rules for a specific section (code_quality, testing, security, architecture)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Section name: code_quality, testing, security, or architecture */
                    section: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rules for the specified section */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SectionRulesResponse"];
                    };
                };
                /** @description Invalid section name */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component configuration
         * @description Returns the current configuration for a specific component
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Component name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Component not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy flow
         * @description Deploys a flow to the runtime
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow deployed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation errors */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start flow
         * @description Starts a deployed flow
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop flow
         * @description Stops a running flow
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow stopped */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent message entries
         * @description Returns the most recent logged messages from the circular buffer
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of entries to return (default: 100, max: 10000) */
                    limit?: number;
                    /** @description Filter by NATS subject pattern */
                    subject?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of message entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageLogEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flowgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component FlowGraph
         * @description Returns the complete FlowGraph with nodes and edges for all managed components
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description FlowGraph with nodes and edges */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all flows
         * @description Returns a list of all visual flows
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of flows */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new flow
         * @description Creates a new visual flow
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flow by ID
         * @description Returns a single flow by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Flow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update flow
         * @description Updates an existing flow
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Version conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete flow
         * @description Deletes a flow
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flows/{id}/runtime/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get runtime health
         * @description Returns health status and timing for flow components (status, uptime, last activity)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Flow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime health status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeHealthResponse"];
                    };
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flows/{id}/runtime/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get runtime messages
         * @description Returns filtered message logger entries for flow components (NATS message flow visibility)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of messages to return (default: 100, max: 1000) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Flow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime message entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeMessagesResponse"];
                    };
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flows/{id}/runtime/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get runtime metrics
         * @description Returns runtime metrics for flow components (throughput, errors, queue depth) with graceful degradation
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Flow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeMetricsResponse"];
                    };
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component flow gaps
         * @description Returns disconnected nodes and orphaned ports in the component flow
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component flow gaps and disconnected nodes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component health status
         * @description Returns aggregated health status for all managed components
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component health information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kv/{bucket}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query KV bucket
         * @description Query NATS KV bucket entries (development/test only)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Key pattern to match (e.g., 'entity.*') */
                    pattern?: string;
                    /** @description Maximum number of entries to return (default: 100, max: 1000) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description KV bucket name */
                    bucket: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KV bucket entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description KV query disabled in production */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bucket not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kv/{bucket}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch KV bucket changes
         * @description Stream KV bucket changes via Server-Sent Events (SSE). Supports pattern filtering and SSE reconnection with event IDs.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Key pattern to watch (e.g., 'entity.*'). Default: '*' (all keys) */
                    pattern?: string;
                };
                header?: never;
                path: {
                    /** @description KV bucket name (e.g., ENTITY_STATES, CONTEXT_INDEX) */
                    bucket: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of KV changes. Events: 'connected' (initial), 'kv_change' (updates), 'error' (failures) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid bucket name or pattern */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bucket not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all components
         * @description Returns a list of all managed components with basic information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of components */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component data paths
         * @description Returns data paths from input components to all reachable components
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data paths through component graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get message statistics
         * @description Returns statistics about processed messages
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Message statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component status
         * @description Returns detailed status for a specific component
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Component name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Component not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket status stream
         * @description Real-time flow status updates via WebSocket.
         *
         *     ## Connection
         *     Connect with: ws://host/flowbuilder/status/stream?flowId={flowId}
         *
         *     ## Message Types (Server → Client)
         *     All messages are wrapped in StatusStreamEnvelope:
         *     - **flow_status**: Flow state changes (deployed, running, stopped, failed)
         *     - **component_health**: Component health updates (every 5s)
         *     - **component_metrics**: Real-time metrics from MetricsForwarder
         *     - **log_entry**: Log messages from LogForwarder
         *
         *     ## Filtering (Client → Server)
         *     Send SubscribeCommand JSON to filter messages:
         *     - message_types: Array of message types to receive
         *     - log_level: Minimum log level (DEBUG < INFO < WARN < ERROR)
         *     - sources: Array of component names to filter by
         *
         *     ## Example Subscribe Command
         *     {"command":"subscribe","message_types":["flow_status","log_entry"],"log_level":"WARN"}
         */
        get: {
            parameters: {
                query: {
                    /** @description Flow ID to subscribe to for status updates */
                    flowId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching to WebSocket protocol */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid flowId parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Flow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get monitored subjects
         * @description Returns list of NATS subjects being monitored
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of monitored subjects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trace/{traceID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get entries by trace ID
         * @description Returns all message entries for a specific W3C trace ID, ordered chronologically
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description W3C trace ID (32 hex characters) */
                    traceID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trace entries found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Invalid trace ID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available component types
         * @description Returns array of component metadata including schemas
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of component types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component type by ID
         * @description Returns metadata and schema for a specific component type
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Component type ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component type metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Component type not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate component flow connectivity
         * @description Performs FlowGraph connectivity analysis for operational validation (used by E2E tests)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow connectivity analysis results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List plans
         * @description Returns all development plans with their current workflow stage and active agent loops
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of plans with status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanWithStatus"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create plan
         * @description Creates a new development plan from a description and triggers the planner agent to generate Goal, Context, and Scope
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan already exists, returns current state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanWithStatus"];
                    };
                };
                /** @description Plan created and planning triggered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatePlanResponse"];
                    };
                };
                /** @description Invalid request (missing description) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get plan
         * @description Returns a single plan with its current workflow stage and active agent loops
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan with current status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanWithStatus"];
                    };
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute plan
         * @description Triggers the batch task dispatcher to execute all tasks for an approved plan
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan execution accepted and started asynchronously */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanWithStatus"];
                    };
                };
                /** @description Plan must be approved before execution */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List phases
         * @description Returns all phases for a plan, ordered by sequence
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of phases for the plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"][];
                    };
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create phase
         * @description Creates a new phase within the plan
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/{phaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get phase
         * @description Returns a single phase by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                    /** @description Phase identifier */
                    phaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"];
                    };
                };
                /** @description Phase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update phase
         * @description Updates a phase's name, description, dependencies, or agent config
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                    /** @description Phase identifier */
                    phaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Phase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete phase
         * @description Deletes a phase and reassigns its tasks to the default phase
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                    /** @description Phase identifier */
                    phaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Phase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/{phaseId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve phase
         * @description Approves a single phase for execution
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                    /** @description Phase identifier */
                    phaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"];
                    };
                };
                /** @description Phase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/{phaseId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject phase
         * @description Rejects a phase with a reason
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                    /** @description Phase identifier */
                    phaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"];
                    };
                };
                /** @description Rejection reason required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Phase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/{phaseId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List phase tasks
         * @description Returns all tasks belonging to a specific phase
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                    /** @description Phase identifier */
                    phaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of tasks for the phase */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
                /** @description Phase not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve all phases
         * @description Bulk-approves all pending phases for a plan
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All phases approved, returns updated phases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"][];
                    };
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate phases
         * @description Triggers the LLM to generate phases from an approved plan's Goal, Context, and Scope
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phase generation accepted and started asynchronously */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AsyncOperationResponse"];
                    };
                };
                /** @description Plan must be approved before generating phases */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/phases/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder phases
         * @description Reorders phases within the plan by specifying new sequence order
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Phases reordered, returns updated phases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Phase"][];
                    };
                };
                /** @description Invalid phase IDs */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote plan
         * @description Approves a plan draft, marking it ready for task generation and execution
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan approved and returned with updated status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanWithStatus"];
                    };
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get plan reviews
         * @description Returns the aggregated review synthesis result for a plan, combining findings from all reviewers
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated review synthesis result with verdict, findings, and per-reviewer summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SynthesisResult"];
                    };
                };
                /** @description Plan not found or no completed review available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List plan tasks
         * @description Returns all tasks associated with the given plan
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of tasks for the plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-api/plans/{slug}/tasks/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate tasks
         * @description Triggers the task generator agent to produce executable tasks from an approved plan's Goal, Context, and Scope
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-friendly plan identifier */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task generation accepted and started asynchronously */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AsyncOperationResponse"];
                    };
                };
                /** @description Plan must be approved before generating tasks */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptanceCriterion: {
            given: string;
            then: string;
            when: string;
        };
        ActiveLoopStatus: {
            loop_id: string;
            role: string;
            state: string;
        };
        ApprovePhaseHTTPRequest: {
            approved_by?: string;
        };
        AsyncOperationResponse: {
            message: string;
            request_id: string;
            slug: string;
            trace_id: string;
        };
        CreatePhaseHTTPRequest: {
            agent_config?: {
                max_concurrent?: number;
                model?: string;
                review_strategy?: string;
                roles?: string[];
            } | null;
            depends_on?: string[];
            description?: string;
            name: string;
            requires_approval?: boolean;
        };
        CreatePlanRequest: {
            description: string;
        };
        CreatePlanResponse: {
            message: string;
            request_id: string;
            slug: string;
            trace_id: string;
        };
        Flow: {
            connections: {
                id: string;
                source_node_id: string;
                source_port: string;
                target_node_id: string;
                target_port: string;
            }[];
            /** Format: date-time */
            created_at: string;
            created_by?: string;
            /** Format: date-time */
            deployed_at?: string | null;
            description?: string;
            id: string;
            /** Format: date-time */
            last_modified: string;
            name: string;
            nodes: {
                component: string;
                config: {
                    [key: string]: unknown;
                };
                id: string;
                name: string;
                position: {
                    x: number;
                    y: number;
                };
                type: string;
            }[];
            runtime_state: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            stopped_at?: string | null;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        FlowStatusPayload: {
            error?: string;
            prev_state: string;
            state: string;
            timestamp: number;
        };
        HTTPCheckRequest: {
            content: string;
            context?: {
                [key: string]: string;
            };
        };
        HTTPCheckResponse: {
            checked_at: string;
            passed: boolean;
            violations?: {
                Location: string;
                Message: string;
                Rule: {
                    Enforced: boolean;
                    ID: string;
                    Priority: string;
                    Text: string;
                };
                Section: string;
            }[];
            warnings?: {
                Location: string;
                Message: string;
                Rule: {
                    Enforced: boolean;
                    ID: string;
                    Priority: string;
                    Text: string;
                };
                Section: string;
            }[];
        };
        LogEntryPayload: {
            fields: {
                [key: string]: unknown;
            };
            level: string;
            message: string;
            source: string;
        };
        MessageLogEntry: {
            message_id?: string;
            message_type?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: byte */
            raw_data?: string;
            sequence: number;
            span_id?: string;
            subject: string;
            summary: string;
            /** Format: date-time */
            timestamp: string;
            trace_id?: string;
        };
        MetricEntry: {
            labels: {
                [key: string]: string;
            };
            name: string;
            type: string;
            value: number;
        };
        MetricsPayload: {
            component: string;
            metrics: {
                labels: {
                    [key: string]: string;
                };
                name: string;
                type: string;
                value: number;
            }[];
        };
        Phase: {
            agent_config?: {
                max_concurrent?: number;
                model?: string;
                review_strategy?: string;
                roles?: string[];
            } | null;
            approved?: boolean;
            /** Format: date-time */
            approved_at?: string | null;
            approved_by?: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            depends_on?: string[];
            description?: string;
            id: string;
            name: string;
            plan_id: string;
            requires_approval?: boolean;
            sequence: number;
            /** Format: date-time */
            started_at?: string | null;
            status: string;
        };
        PhaseAgentConfig: {
            max_concurrent?: number;
            model?: string;
            review_strategy?: string;
            roles?: string[];
        };
        PhaseStats: {
            active: number;
            blocked: number;
            complete: number;
            failed: number;
            pending: number;
            ready: number;
            total: number;
        };
        PhaseStatus: string;
        Plan: {
            approved: boolean;
            /** Format: date-time */
            approved_at?: string | null;
            context?: string;
            /** Format: date-time */
            created_at: string;
            execution_trace_ids?: string[];
            goal?: string;
            id: string;
            last_error?: string;
            /** Format: date-time */
            last_error_at?: string | null;
            llm_call_history?: {
                phase_review?: {
                    iteration: number;
                    llm_request_ids: string[];
                    verdict?: string;
                }[];
                plan_review?: {
                    iteration: number;
                    llm_request_ids: string[];
                    verdict?: string;
                }[];
                task_review?: {
                    iteration: number;
                    llm_request_ids: string[];
                    verdict?: string;
                }[];
            } | null;
            /** Format: byte */
            phase_review_findings?: string;
            phase_review_formatted_findings?: string;
            phase_review_iteration?: number;
            phase_review_summary?: string;
            phase_review_verdict?: string;
            /** Format: date-time */
            phase_reviewed_at?: string | null;
            phases_approved?: boolean;
            /** Format: date-time */
            phases_approved_at?: string | null;
            project_id: string;
            /** Format: byte */
            review_findings?: string;
            review_formatted_findings?: string;
            review_iteration?: number;
            review_summary?: string;
            review_verdict?: string;
            /** Format: date-time */
            reviewed_at?: string | null;
            scope?: {
                do_not_touch?: string[];
                exclude?: string[];
                include?: string[];
            };
            slug: string;
            status?: string;
            /** Format: byte */
            task_review_findings?: string;
            task_review_formatted_findings?: string;
            task_review_iteration?: number;
            task_review_summary?: string;
            task_review_verdict?: string;
            /** Format: date-time */
            task_reviewed_at?: string | null;
            tasks_approved?: boolean;
            /** Format: date-time */
            tasks_approved_at?: string | null;
            title: string;
        };
        PlanWithStatus: {
            active_loops: {
                loop_id: string;
                role: string;
                state: string;
            }[];
            approved: boolean;
            /** Format: date-time */
            approved_at?: string | null;
            context?: string;
            /** Format: date-time */
            created_at: string;
            execution_trace_ids?: string[];
            goal?: string;
            id: string;
            last_error?: string;
            /** Format: date-time */
            last_error_at?: string | null;
            llm_call_history?: {
                phase_review?: {
                    iteration: number;
                    llm_request_ids: string[];
                    verdict?: string;
                }[];
                plan_review?: {
                    iteration: number;
                    llm_request_ids: string[];
                    verdict?: string;
                }[];
                task_review?: {
                    iteration: number;
                    llm_request_ids: string[];
                    verdict?: string;
                }[];
            } | null;
            /** Format: byte */
            phase_review_findings?: string;
            phase_review_formatted_findings?: string;
            phase_review_iteration?: number;
            phase_review_summary?: string;
            phase_review_verdict?: string;
            /** Format: date-time */
            phase_reviewed_at?: string | null;
            phases_approved?: boolean;
            /** Format: date-time */
            phases_approved_at?: string | null;
            project_id: string;
            /** Format: byte */
            review_findings?: string;
            review_formatted_findings?: string;
            review_iteration?: number;
            review_summary?: string;
            review_verdict?: string;
            /** Format: date-time */
            reviewed_at?: string | null;
            scope?: {
                do_not_touch?: string[];
                exclude?: string[];
                include?: string[];
            };
            slug: string;
            stage: string;
            status?: string;
            /** Format: byte */
            task_review_findings?: string;
            task_review_formatted_findings?: string;
            task_review_iteration?: number;
            task_review_summary?: string;
            task_review_verdict?: string;
            /** Format: date-time */
            task_reviewed_at?: string | null;
            tasks_approved?: boolean;
            /** Format: date-time */
            tasks_approved_at?: string | null;
            title: string;
        };
        RejectPhaseHTTPRequest: {
            reason: string;
        };
        ReloadResponse: {
            message?: string;
            rule_count: number;
            success: boolean;
        };
        ReorderPhasesHTTPRequest: {
            phase_ids: string[];
        };
        Response: {
            created_at: string;
            id: string;
            modified_at: string;
            project: string;
            rule_count: number;
            sections: {
                [key: string]: {
                    Enforced: boolean;
                    ID: string;
                    Priority: string;
                    Text: string;
                }[];
            };
            version: string;
        };
        ReviewFinding: {
            category?: string;
            cwe?: string;
            file: string;
            issue: string;
            line: number;
            role?: string;
            severity: string;
            sop_id?: string;
            status?: string;
            suggestion: string;
        };
        ReviewerSummary: {
            finding_count: number;
            passed: boolean;
            role: string;
            summary: string;
        };
        Rule: {
            Enforced: boolean;
            ID: string;
            Priority: string;
            Text: string;
        };
        RuleWithSection: {
            enforced: boolean;
            id: string;
            priority: string;
            section: string;
            text: string;
        };
        RulesResponse: {
            count: number;
            rules: {
                enforced: boolean;
                id: string;
                priority: string;
                section: string;
                text: string;
            }[];
        };
        RuntimeHealthResponse: {
            components: {
                component: string;
                details: unknown;
                healthy: boolean;
                /** Format: date-time */
                last_activity?: string | null;
                message: string;
                name: string;
                /** Format: date-time */
                start_time?: string | null;
                status: string;
                type: string;
                uptime_seconds?: number | null;
            }[];
            overall: {
                degraded_count: number;
                error_count: number;
                running_count: number;
                status: string;
            };
            /** Format: date-time */
            timestamp: string;
        };
        RuntimeMessagesResponse: {
            limit: number;
            messages: {
                component: string;
                direction: string;
                message_id: string;
                message_type?: string;
                metadata?: {
                    [key: string]: unknown;
                };
                subject: string;
                summary: string;
                timestamp: string;
            }[];
            note?: string;
            timestamp: string;
            total: number;
        };
        RuntimeMetricsResponse: {
            components: {
                component: string;
                error_rate?: number | null;
                name: string;
                queue_depth?: number | null;
                raw_counters?: {
                    [key: string]: number;
                } | null;
                status: string;
                throughput?: number | null;
                type: string;
            }[];
            prometheus_available: boolean;
            /** Format: date-time */
            timestamp: string;
        };
        Scope: {
            do_not_touch?: string[];
            exclude?: string[];
            include?: string[];
        };
        SectionRulesResponse: {
            count: number;
            rules: {
                Enforced: boolean;
                ID: string;
                Priority: string;
                Text: string;
            }[];
            section: string;
        };
        StatusStreamEnvelope: {
            flow_id: string;
            id: string;
            /** Format: byte */
            payload?: string;
            timestamp: number;
            type: string;
        };
        SubscribeCommand: {
            command: string;
            log_level?: string;
            message_types?: string[];
            sources?: string[];
        };
        SynthesisResult: {
            findings: {
                category?: string;
                cwe?: string;
                file: string;
                issue: string;
                line: number;
                role?: string;
                severity: string;
                sop_id?: string;
                status?: string;
                suggestion: string;
            }[];
            passed: boolean;
            reviewers: {
                finding_count: number;
                passed: boolean;
                role: string;
                summary: string;
            }[];
            stats: {
                by_reviewer: {
                    [key: string]: number;
                };
                by_severity: {
                    [key: string]: number;
                };
                reviewers_passed: number;
                reviewers_total: number;
                total_findings: number;
            };
            summary: string;
            verdict: string;
        };
        SynthesisStats: {
            by_reviewer: {
                [key: string]: number;
            };
            by_severity: {
                [key: string]: number;
            };
            reviewers_passed: number;
            reviewers_total: number;
            total_findings: number;
        };
        Task: {
            acceptance_criteria: {
                given: string;
                then: string;
                when: string;
            }[];
            /** Format: date-time */
            approved_at?: string | null;
            approved_by?: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            depends_on?: string[];
            description: string;
            /** Format: date-time */
            escalated_at?: string | null;
            escalation_feedback?: string;
            escalation_iteration?: number;
            escalation_reason?: string;
            files?: string[];
            id: string;
            last_error?: string;
            /** Format: date-time */
            last_error_at?: string | null;
            phase_id: string;
            plan_id: string;
            rejection_reason?: string;
            sequence: number;
            /** Format: date-time */
            started_at?: string | null;
            status: string;
            type?: string;
        };
        UpdatePhaseHTTPRequest: {
            agent_config?: {
                max_concurrent?: number;
                model?: string;
                review_strategy?: string;
                roles?: string[];
            } | null;
            depends_on?: string[];
            description?: string | null;
            name?: string | null;
            requires_approval?: boolean | null;
        };
        Violation: {
            Location: string;
            Message: string;
            Rule: {
                Enforced: boolean;
                ID: string;
                Priority: string;
                Text: string;
            };
            Section: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
