package payloads

import (
	"encoding/json"
	"fmt"

	"github.com/c360studio/semstreams/message"
)

// RecoveryActionKind enumerates the closed action set a wedge-recovery agent
// can return per ADR-037. Adding a new kind requires an ADR addendum + payload
// re-registration; the closed set keeps recovery agents inside an approved
// blast radius and prevents arbitrary state mutation.
type RecoveryActionKind string

const (
	// RecoveryActionRefinePrompt — rewrite the wedged agent's task prompt with
	// explicit context the agent missed (e.g. "graph_search showed
	// `[project] org.sensorhub`; use that"). Recovery's first reach when the
	// trajectory shows the agent had the answer in front of it but didn't act.
	RecoveryActionRefinePrompt RecoveryActionKind = "refine_prompt"

	// RecoveryActionNarrowScope — reduce the task's scope (e.g. split a
	// multi-file change into one file at a time). Used when the trajectory
	// shows the agent thrashing across files because the task was too broad.
	RecoveryActionNarrowScope RecoveryActionKind = "narrow_scope"

	// RecoveryActionSplitReq — decompose the requirement into smaller
	// requirements. Heavier action than narrow_scope; mutates plan structure.
	// Reserved for cases where the plan-level decomposition was clearly wrong.
	RecoveryActionSplitReq RecoveryActionKind = "split_req"

	// RecoveryActionEscalateHuman — recovery agent has analysed the wedge
	// and produced a diagnosis but cannot pick a programmatic action. Surfaces
	// in the UI with the diagnosis text. The good failure mode — analysis is
	// the deliverable.
	RecoveryActionEscalateHuman RecoveryActionKind = "escalate_human"

	// RecoveryActionMarkUnrecoverable — recovery agent has determined the
	// wedge cannot succeed from current state regardless of refinements
	// (e.g. upstream artifact doesn't exist, fixture is malformed). Plan
	// continues with reduced scope or fails cleanly with diagnostic.
	RecoveryActionMarkUnrecoverable RecoveryActionKind = "mark_unrecoverable"
)

// RecoveryLayer identifies which recovery layer attempted the action. Per
// ADR-037 three-guardrails: phase-local recovery gets one shot, then
// coordinator gets one shot, then human. The next layer keys off the prior
// layer's record to avoid attempting the same recovery shape twice.
type RecoveryLayer string

const (
	// RecoveryLayerPhaseLocal — recovery dispatched by the same component
	// whose escalation triggered it (plan-manager for plan-phase wedges,
	// execution-manager for TDD-cycle wedges).
	RecoveryLayerPhaseLocal RecoveryLayer = "phase_local"

	// RecoveryLayerCoordinator — recovery dispatched by the dedicated
	// coordinator component (Stage 2) when phase-local recovery exhausted
	// or when the wedge crosses phase boundaries (QA failures, cross-req
	// contract mismatches).
	RecoveryLayerCoordinator RecoveryLayer = "coordinator"
)

// RecoveryRequestedType is the message type emitted on
// recovery.requested.<slug> when an escalating component asks for recovery.
// Async dispatch per ADR-037 stage-1 design lock — the escalating component
// emits this and continues, listens for RecoveryComplete on
// recovery.complete.<slug> via the standard reconciliation path.
var RecoveryRequestedType = message.Type{
	Domain:   "workflow",
	Category: "recovery-requested",
	Version:  "v1",
}

// RecoveryRequested carries the wedge context a recovery agent needs to
// diagnose. Per ADR-037 stage-1 design lock #2: full trajectory (capped at
// 80 steps via internal/trajectory.DefaultLogStepLimit) + plan/req state +
// last-failure feedback + referenced graph entity IDs.
//
// Wire semantics:
//   - Published on recovery.requested.<slug> via the WORKFLOW JetStream
//     stream. Subject family chosen to mirror existing workflow.events.>
//     conventions; recovery is itself a workflow event class.
//   - Consumed by phase-local recovery (when wired into plan-manager and
//     execution-manager Stage-1 escalation paths) or by the coordinator
//     component (Stage 2). The Layer field disambiguates.
type RecoveryRequested struct {
	// RecoveryID is a UUID generated by the escalating component, used as
	// the primary key in RECOVERY_STATES KV. The matching RecoveryComplete
	// message echoes this back so the watcher can reconcile.
	RecoveryID string `json:"recovery_id"`

	// Layer identifies the recovery layer this request targets — phase-local
	// for first-attempt recovery, coordinator for second-attempt or
	// cross-phase wedges.
	Layer RecoveryLayer `json:"layer"`

	// Slug is the plan slug — routing key and trace-deep-link.
	Slug string `json:"slug"`

	// RequirementID is set when the wedge is requirement-scoped. Empty for
	// plan-phase wedges that don't bind to a single requirement.
	RequirementID string `json:"requirement_id,omitempty"`

	// TaskID identifies the specific TDD task that wedged. Empty for
	// plan-phase wedges.
	TaskID string `json:"task_id,omitempty"`

	// LoopID is the agentic-loop ID of the wedged agent. Strongly recommended
	// — the recovery agent fetches the full trajectory via internal/trajectory
	// when set, which is the load-bearing input per ADR-037 design lock #2.
	// Optional because plan-phase wedges don't yet plumb the wedged generator's
	// loop ID through RevisionMutationRequest (TODO: track on workflow.Plan).
	// When empty, the recovery agent falls back to feedback + findings only.
	// For execution-phase wedges this is exec.DeveloperLoopID (always set).
	LoopID string `json:"loop_id,omitempty"`

	// EscalationReason is the human-readable reason the escalating component
	// recorded (e.g. "fixable rejections exceeded TDD cycle budget", "plan
	// review revision cap reached"). Carries the wedge classification at
	// the source rather than asking the recovery agent to re-derive it.
	EscalationReason string `json:"escalation_reason"`

	// LastFailureFeedback is the most recent reviewer/validator feedback
	// shown to the wedged agent before escalation. Recovery agent reads this
	// alongside the trajectory to understand what the agent was responding
	// to (or failing to respond to). Empty when the wedge wasn't review-
	// driven (e.g. iter=N tool exhaustion).
	LastFailureFeedback string `json:"last_failure_feedback,omitempty"`

	// PriorRecoveryID is set when this recovery request is the second-layer
	// (coordinator) attempt after a phase-local recovery already failed.
	// Coordinator agent reads the prior recovery record from RECOVERY_STATES
	// to avoid attempting the same action shape twice.
	PriorRecoveryID string `json:"prior_recovery_id,omitempty"`

	// TraceID for end-to-end correlation across the recovery flow.
	TraceID string `json:"trace_id,omitempty"`
}

// Schema implements message.Payload.
func (r *RecoveryRequested) Schema() message.Type { return RecoveryRequestedType }

// Validate implements message.Payload.
func (r *RecoveryRequested) Validate() error {
	if r.RecoveryID == "" {
		return fmt.Errorf("recovery_id is required")
	}
	if r.Layer == "" {
		return fmt.Errorf("layer is required")
	}
	if r.Layer != RecoveryLayerPhaseLocal && r.Layer != RecoveryLayerCoordinator {
		return fmt.Errorf("layer must be phase_local or coordinator, got %q", r.Layer)
	}
	if r.Slug == "" {
		return fmt.Errorf("slug is required")
	}
	if r.EscalationReason == "" {
		return fmt.Errorf("escalation_reason is required")
	}
	return nil
}

// MarshalJSON implements json.Marshaler.
func (r *RecoveryRequested) MarshalJSON() ([]byte, error) {
	type Alias RecoveryRequested
	return json.Marshal((*Alias)(r))
}

// UnmarshalJSON implements json.Unmarshaler.
func (r *RecoveryRequested) UnmarshalJSON(data []byte) error {
	type Alias RecoveryRequested
	return json.Unmarshal(data, (*Alias)(r))
}

// RecoveryCompleteType is emitted on recovery.complete.<slug> when a
// recovery agent finishes a recovery attempt (regardless of outcome).
// Carries the chosen RecoveryAction so the original escalating component's
// watcher can reconcile state and either re-dispatch (refine_prompt /
// narrow_scope / split_req) or terminate cleanly (escalate_human /
// mark_unrecoverable).
var RecoveryCompleteType = message.Type{
	Domain:   "workflow",
	Category: "recovery-complete",
	Version:  "v1",
}

// RecoveryComplete is the recovery agent's submit_work output translated to
// the wire. Per ADR-037 stage-1 design lock #3: distinct outcome semantics
// for recovery success vs failure, with the action record persisted in
// RECOVERY_STATES KV under recovery_id.
type RecoveryComplete struct {
	// RecoveryID echoes the matching RecoveryRequested.RecoveryID.
	RecoveryID string `json:"recovery_id"`

	// Layer echoes the matching RecoveryRequested.Layer.
	Layer RecoveryLayer `json:"layer"`

	// Slug echoes the matching RecoveryRequested.Slug — routing key.
	Slug string `json:"slug"`

	// Action is the recovery agent's chosen action from the closed set.
	// Required.
	Action RecoveryActionKind `json:"action"`

	// Diagnosis is the recovery agent's analysis of the wedge — required
	// for every action including escalate_human and mark_unrecoverable.
	// This is what surfaces in the UI for human-attention paths and what
	// the lessons pipeline (ADR-033) consumes for long-loop learning.
	Diagnosis string `json:"diagnosis"`

	// RefinedPrompt is set when Action is refine_prompt — the new prompt
	// the recovery agent wants the wedged agent to retry with. Required
	// when Action == refine_prompt; empty otherwise.
	RefinedPrompt string `json:"refined_prompt,omitempty"`

	// ScopeChanges captures structured scope adjustments for narrow_scope
	// and split_req actions. Free-form JSON to keep the payload schema
	// stable while the action handlers evolve. Empty for actions that
	// don't mutate scope.
	ScopeChanges json.RawMessage `json:"scope_changes,omitempty"`

	// RecoverySucceeded is the recovery agent's own assessment. False
	// when Action is escalate_human or mark_unrecoverable, OR when the
	// recovery agent's submit_work itself failed (loop crashed, parse
	// error, etc.). The escalating component's watcher uses this to
	// distinguish outcome=recovery_failed from outcome=recovered.
	RecoverySucceeded bool `json:"recovery_succeeded"`

	// RecoveryAgentLoopID is the agentic-loop ID of the recovery agent
	// itself. Carried so the lessons pipeline can pull the recovery
	// trajectory when learning from recovery patterns (per ADR-037 stage-1
	// design lock #3 — recovery_failed is itself a learnable event).
	RecoveryAgentLoopID string `json:"recovery_agent_loop_id"`

	// TraceID for end-to-end correlation.
	TraceID string `json:"trace_id,omitempty"`
}

// Schema implements message.Payload.
func (r *RecoveryComplete) Schema() message.Type { return RecoveryCompleteType }

// Validate implements message.Payload.
func (r *RecoveryComplete) Validate() error {
	if r.RecoveryID == "" {
		return fmt.Errorf("recovery_id is required")
	}
	if r.Slug == "" {
		return fmt.Errorf("slug is required")
	}
	if r.Action == "" {
		return fmt.Errorf("action is required")
	}
	switch r.Action {
	case RecoveryActionRefinePrompt,
		RecoveryActionNarrowScope,
		RecoveryActionSplitReq,
		RecoveryActionEscalateHuman,
		RecoveryActionMarkUnrecoverable:
		// valid
	default:
		return fmt.Errorf("action must be one of refine_prompt|narrow_scope|split_req|escalate_human|mark_unrecoverable, got %q", r.Action)
	}
	if r.Action == RecoveryActionRefinePrompt && r.RefinedPrompt == "" {
		return fmt.Errorf("refined_prompt is required when action is refine_prompt")
	}
	if r.Diagnosis == "" {
		return fmt.Errorf("diagnosis is required (every action including escalate_human/mark_unrecoverable needs analysis)")
	}
	if r.RecoveryAgentLoopID == "" {
		return fmt.Errorf("recovery_agent_loop_id is required (lessons pipeline keys off it)")
	}
	return nil
}

// MarshalJSON implements json.Marshaler.
func (r *RecoveryComplete) MarshalJSON() ([]byte, error) {
	type Alias RecoveryComplete
	return json.Marshal((*Alias)(r))
}

// UnmarshalJSON implements json.Unmarshaler.
func (r *RecoveryComplete) UnmarshalJSON(data []byte) error {
	type Alias RecoveryComplete
	return json.Unmarshal(data, (*Alias)(r))
}

// RecoveryStatesBucket is the JetStream KV bucket name that holds the
// durable record of recovery attempts (which layer ran, what action was
// chosen, outcome). Reconciled on plan-manager + execution-manager startup
// like other manager-pattern state. Per ADR-037 stage-1 plumbing item #1.
const RecoveryStatesBucket = "RECOVERY_STATES"

// Recovery NATS subject family. The escalating component publishes
// RecoveryRequested on RecoveryRequestedSubjectPrefix + slug; the recovery
// agent (phase-local or coordinator) consumes the request and emits
// RecoveryComplete on RecoveryCompleteSubjectPrefix + slug. The escalating
// component's watcher subscribes to the complete subject for reconciliation.
const (
	RecoveryRequestedSubjectPrefix = "recovery.requested."
	RecoveryCompleteSubjectPrefix  = "recovery.complete."
)
